//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.03 at 10:42:35 PM CEST 
//


package net.sophis.sophis.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AxisLabels.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AxisLabels">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Underlying"/>
 *     &lt;enumeration value="Rate"/>
 *     &lt;enumeration value="Volat"/>
 *     &lt;enumeration value="Maturity"/>
 *     &lt;enumeration value="Credit Risk"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AxisLabels")
@XmlEnum
public enum AxisLabels {

    @XmlEnumValue("Underlying")
    UNDERLYING("Underlying"),
    @XmlEnumValue("Rate")
    RATE("Rate"),
    @XmlEnumValue("Volat")
    VOLAT("Volat"),
    @XmlEnumValue("Maturity")
    MATURITY("Maturity"),
    @XmlEnumValue("Credit Risk")
    CREDIT_RISK("Credit Risk");
    private final String value;

    AxisLabels(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AxisLabels fromValue(String v) {
        for (AxisLabels c: AxisLabels.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
