//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.03 at 10:42:35 PM CEST 
//


package net.sophis.sophis.common;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.sophis.sophis.common package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SnapshotBaseline_QNAME = new QName("http://sophis.net/sophis/common", "snapshotBaseline");
    private final static QName _ExtraFields_QNAME = new QName("http://sophis.net/sophis/common", "extraFields");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.sophis.sophis.common
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SnapshotBaseline }
     * 
     */
    public SnapshotBaseline createSnapshotBaseline() {
        return new SnapshotBaseline();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link BusinessDayAdjustmentsReference }
     * 
     */
    public BusinessDayAdjustmentsReference createBusinessDayAdjustmentsReference() {
        return new BusinessDayAdjustmentsReference();
    }

    /**
     * Create an instance of {@link ExtraFields }
     * 
     */
    public ExtraFields createExtraFields() {
        return new ExtraFields();
    }

    /**
     * Create an instance of {@link ReferencableTime }
     * 
     */
    public ReferencableTime createReferencableTime() {
        return new ReferencableTime();
    }

    /**
     * Create an instance of {@link DateRelativeTo }
     * 
     */
    public DateRelativeTo createDateRelativeTo() {
        return new DateRelativeTo();
    }

    /**
     * Create an instance of {@link ReferencableChar }
     * 
     */
    public ReferencableChar createReferencableChar() {
        return new ReferencableChar();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link ReferencableBinary }
     * 
     */
    public ReferencableBinary createReferencableBinary() {
        return new ReferencableBinary();
    }

    /**
     * Create an instance of {@link AdjustableOrRelativeDate }
     * 
     */
    public AdjustableOrRelativeDate createAdjustableOrRelativeDate() {
        return new AdjustableOrRelativeDate();
    }

    /**
     * Create an instance of {@link DateInterval }
     * 
     */
    public DateInterval createDateInterval() {
        return new DateInterval();
    }

    /**
     * Create an instance of {@link AdjustableDate }
     * 
     */
    public AdjustableDate createAdjustableDate() {
        return new AdjustableDate();
    }

    /**
     * Create an instance of {@link IdentifiedDate }
     * 
     */
    public IdentifiedDate createIdentifiedDate() {
        return new IdentifiedDate();
    }

    /**
     * Create an instance of {@link ReferencableDateTime }
     * 
     */
    public ReferencableDateTime createReferencableDateTime() {
        return new ReferencableDateTime();
    }

    /**
     * Create an instance of {@link RelativeDateOffset }
     * 
     */
    public RelativeDateOffset createRelativeDateOffset() {
        return new RelativeDateOffset();
    }

    /**
     * Create an instance of {@link BusinessCentersReference }
     * 
     */
    public BusinessCentersReference createBusinessCentersReference() {
        return new BusinessCentersReference();
    }

    /**
     * Create an instance of {@link ReferencableString }
     * 
     */
    public ReferencableString createReferencableString() {
        return new ReferencableString();
    }

    /**
     * Create an instance of {@link BusinessCenter }
     * 
     */
    public BusinessCenter createBusinessCenter() {
        return new BusinessCenter();
    }

    /**
     * Create an instance of {@link ReferencableInt }
     * 
     */
    public ReferencableInt createReferencableInt() {
        return new ReferencableInt();
    }

    /**
     * Create an instance of {@link SnapshotTimestamp }
     * 
     */
    public SnapshotTimestamp createSnapshotTimestamp() {
        return new SnapshotTimestamp();
    }

    /**
     * Create an instance of {@link Offset }
     * 
     */
    public Offset createOffset() {
        return new Offset();
    }

    /**
     * Create an instance of {@link ReferencableFloat }
     * 
     */
    public ReferencableFloat createReferencableFloat() {
        return new ReferencableFloat();
    }

    /**
     * Create an instance of {@link ReferencableLong }
     * 
     */
    public ReferencableLong createReferencableLong() {
        return new ReferencableLong();
    }

    /**
     * Create an instance of {@link IntradocumentReference }
     * 
     */
    public IntradocumentReference createIntradocumentReference() {
        return new IntradocumentReference();
    }

    /**
     * Create an instance of {@link ReferencableXMLDocument }
     * 
     */
    public ReferencableXMLDocument createReferencableXMLDocument() {
        return new ReferencableXMLDocument();
    }

    /**
     * Create an instance of {@link BusinessCenters }
     * 
     */
    public BusinessCenters createBusinessCenters() {
        return new BusinessCenters();
    }

    /**
     * Create an instance of {@link StreetAddress }
     * 
     */
    public StreetAddress createStreetAddress() {
        return new StreetAddress();
    }

    /**
     * Create an instance of {@link ReferencableDate }
     * 
     */
    public ReferencableDate createReferencableDate() {
        return new ReferencableDate();
    }

    /**
     * Create an instance of {@link BusinessDayAdjustments }
     * 
     */
    public BusinessDayAdjustments createBusinessDayAdjustments() {
        return new BusinessDayAdjustments();
    }

    /**
     * Create an instance of {@link ReferencableDouble }
     * 
     */
    public ReferencableDouble createReferencableDouble() {
        return new ReferencableDouble();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SnapshotBaseline }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sophis.net/sophis/common", name = "snapshotBaseline")
    public JAXBElement<SnapshotBaseline> createSnapshotBaseline(SnapshotBaseline value) {
        return new JAXBElement<SnapshotBaseline>(_SnapshotBaseline_QNAME, SnapshotBaseline.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtraFields }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sophis.net/sophis/common", name = "extraFields")
    public JAXBElement<ExtraFields> createExtraFields(ExtraFields value) {
        return new JAXBElement<ExtraFields>(_ExtraFields_QNAME, ExtraFields.class, null, value);
    }

}
