//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.03 at 10:42:35 PM CEST 
//


package net.sophis.sophis.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersistenceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PersistenceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Create"/>
 *     &lt;enumeration value="Anonymous"/>
 *     &lt;enumeration value="FindOrCreate"/>
 *     &lt;enumeration value="Universal"/>
 *     &lt;enumeration value="UpdateOrCreate"/>
 *     &lt;enumeration value="Shared"/>
 *     &lt;enumeration value="CheckOrCreate"/>
 *     &lt;enumeration value="Check"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PersistenceType")
@XmlEnum
public enum PersistenceType {


    /**
     * Replaces "Anonymous" since 6.1.
     * 
     */
    @XmlEnumValue("Create")
    CREATE("Create"),

    /**
     * Deprecated since 6.1. Use "Create" instead. Keep it for compatibility reasons.
     * 						The entity only has a meaning within
     * 					 	the scope of the document but still needs to be persistent.
     * 						It is an error that such an entity, is provided a primary key 
     * 						in its description, and it is awkward that it owns
     * 						an external reference.
     * 
     */
    @XmlEnumValue("Anonymous")
    ANONYMOUS("Anonymous"),

    /**
     * Replaces "Universal" since 6.1.
     * 
     */
    @XmlEnumValue("FindOrCreate")
    FIND_OR_CREATE("FindOrCreate"),

    /**
     * Deprecated since 6.1. Use "FindOrCreate" instead. Keep it for compatibility reasons.
     * 						The entity definition never changes, it will be created
     * 						in db only once if it does not exist already.
     * 
     */
    @XmlEnumValue("Universal")
    UNIVERSAL("Universal"),

    /**
     * Replaces "Shared" since 6.1.
     * 
     */
    @XmlEnumValue("UpdateOrCreate")
    UPDATE_OR_CREATE("UpdateOrCreate"),

    /**
     * Deprecated since 6.1. Use "UpdateOrCreate" instead. Keep it for compatibility reasons.
     * 						The entity definition may change, it will be created in
     * 						db if it does not exist, and updated otherwise.
     * 
     */
    @XmlEnumValue("Shared")
    SHARED("Shared"),

    /**
     * The entity definition never changes, it will be created
     *             			in db only once if it does not exist already. Moreover, given description is 
     * 						compared to original description.
     * 
     */
    @XmlEnumValue("CheckOrCreate")
    CHECK_OR_CREATE("CheckOrCreate"),

    /**
     * The entity definition never changes, it will be created
     *             			in db only once if it does not exist already. Moreover, given description is 
     * 						compared to original description.
     * 
     */
    @XmlEnumValue("Check")
    CHECK("Check");
    private final String value;

    PersistenceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PersistenceType fromValue(String v) {
        for (PersistenceType c: PersistenceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
