//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.03 at 10:42:35 PM CEST 
//


package net.sophis.sophis.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QuotationSideEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QuotationSideEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Open"/>
 *     &lt;enumeration value="Last"/>
 *     &lt;enumeration value="High"/>
 *     &lt;enumeration value="Low"/>
 *     &lt;enumeration value="Bid"/>
 *     &lt;enumeration value="Ask"/>
 *     &lt;enumeration value="Mid"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "QuotationSideEnum")
@XmlEnum
public enum QuotationSideEnum {


    /**
     * Client open quotation.
     * 
     */
    @XmlEnumValue("Open")
    OPEN("Open"),

    /**
     * Client close quotation.
     * 
     */
    @XmlEnumValue("Last")
    LAST("Last"),

    /**
     * Client High quotation.
     * 
     */
    @XmlEnumValue("High")
    HIGH("High"),

    /**
     * Client Low quotation.
     * 
     */
    @XmlEnumValue("Low")
    LOW("Low"),

    /**
     * Client Bid quotation.
     * 
     */
    @XmlEnumValue("Bid")
    BID("Bid"),

    /**
     * Client Ask quotation.
     * 
     */
    @XmlEnumValue("Ask")
    ASK("Ask"),

    /**
     * Not implemented.
     * 
     */
    @XmlEnumValue("Mid")
    MID("Mid");
    private final String value;

    QuotationSideEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static QuotationSideEnum fromValue(String v) {
        for (QuotationSideEnum c: QuotationSideEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
