//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.03 at 10:42:35 PM CEST 
//


package net.sophis.reporting;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.sophis.reporting package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Root_QNAME = new QName("http://www.sophis.net/reporting", "root");
    private final static QName _TradeUnderlyingReference_QNAME = new QName("http://www.sophis.net/reporting", "underlyingReference");
    private final static QName _TradeCurrency_QNAME = new QName("http://www.sophis.net/reporting", "currency");
    private final static QName _TradeChangeRate_QNAME = new QName("http://www.sophis.net/reporting", "changeRate");
    private final static QName _TradeComponentReference_QNAME = new QName("http://www.sophis.net/reporting", "componentReference");
    private final static QName _TradeBeneficiaryANBankCpty_QNAME = new QName("http://www.sophis.net/reporting", "beneficiaryANBankCpty");
    private final static QName _TradeKindOfOption_QNAME = new QName("http://www.sophis.net/reporting", "kindOfOption");
    private final static QName _TradeNominal_QNAME = new QName("http://www.sophis.net/reporting", "nominal");
    private final static QName _TradeInternalOrderId_QNAME = new QName("http://www.sophis.net/reporting", "internalOrderId");
    private final static QName _TradePriceType_QNAME = new QName("http://www.sophis.net/reporting", "priceType");
    private final static QName _TradeNegotiationDate_QNAME = new QName("http://www.sophis.net/reporting", "negotiationDate");
    private final static QName _TradeRight_QNAME = new QName("http://www.sophis.net/reporting", "right");
    private final static QName _TradeTradeDate_QNAME = new QName("http://www.sophis.net/reporting", "tradeDate");
    private final static QName _TradeValueDate_QNAME = new QName("http://www.sophis.net/reporting", "valueDate");
    private final static QName _TradeBroker_QNAME = new QName("http://www.sophis.net/reporting", "broker");
    private final static QName _TradeParentId_QNAME = new QName("http://www.sophis.net/reporting", "parentId");
    private final static QName _TradeInstrumentReference_QNAME = new QName("http://www.sophis.net/reporting", "instrumentReference");
    private final static QName _TradeSicovam_QNAME = new QName("http://www.sophis.net/reporting", "sicovam");
    private final static QName _TradeInstrumentType_QNAME = new QName("http://www.sophis.net/reporting", "instrumentType");
    private final static QName _TradePnLDate_QNAME = new QName("http://www.sophis.net/reporting", "pnLDate");
    private final static QName _TradeFxCcy2_QNAME = new QName("http://www.sophis.net/reporting", "fxCcy2");
    private final static QName _TradeQuantity_QNAME = new QName("http://www.sophis.net/reporting", "quantity");
    private final static QName _TradeFxCcy1_QNAME = new QName("http://www.sophis.net/reporting", "fxCcy1");
    private final static QName _TradeNetAmount_QNAME = new QName("http://www.sophis.net/reporting", "netAmount");
    private final static QName _TradeStrike_QNAME = new QName("http://www.sophis.net/reporting", "strike");
    private final static QName _TradeCounterparty_QNAME = new QName("http://www.sophis.net/reporting", "counterparty");
    private final static QName _TradeTime_QNAME = new QName("http://www.sophis.net/reporting", "time");
    private final static QName _TradePaymentDate_QNAME = new QName("http://www.sophis.net/reporting", "paymentDate");
    private final static QName _TradeEntity_QNAME = new QName("http://www.sophis.net/reporting", "entity");
    private final static QName _TradeTradeId_QNAME = new QName("http://www.sophis.net/reporting", "tradeId");
    private final static QName _TradeUnderlyingIsin_QNAME = new QName("http://www.sophis.net/reporting", "underlyingIsin");
    private final static QName _TradeFund_QNAME = new QName("http://www.sophis.net/reporting", "fund");
    private final static QName _TradeNetPrice_QNAME = new QName("http://www.sophis.net/reporting", "netPrice");
    private final static QName _TradeGrossPrice_QNAME = new QName("http://www.sophis.net/reporting", "grossPrice");
    private final static QName _TradeInstrumentAllotment_QNAME = new QName("http://www.sophis.net/reporting", "instrumentAllotment");
    private final static QName _TradeInstrumentMarket_QNAME = new QName("http://www.sophis.net/reporting", "instrumentMarket");
    private final static QName _TradeKernelWorkflow_QNAME = new QName("http://www.sophis.net/reporting", "kernelWorkflow");
    private final static QName _TradeCurrencyType_QNAME = new QName("http://www.sophis.net/reporting", "currencyType");
    private final static QName _TradeIdent_QNAME = new QName("http://www.sophis.net/reporting", "ident");
    private final static QName _TradeFxNominalCcy1_QNAME = new QName("http://www.sophis.net/reporting", "fxNominalCcy1");
    private final static QName _TradeFxNominalCcy2_QNAME = new QName("http://www.sophis.net/reporting", "fxNominalCcy2");
    private final static QName _TradeInstrumentCurrency_QNAME = new QName("http://www.sophis.net/reporting", "instrumentCurrency");
    private final static QName _TradeMarketFees_QNAME = new QName("http://www.sophis.net/reporting", "marketFees");
    private final static QName _TradeBusinessEvent_QNAME = new QName("http://www.sophis.net/reporting", "businessEvent");
    private final static QName _TradeAccruedCoupon_QNAME = new QName("http://www.sophis.net/reporting", "accruedCoupon");
    private final static QName _TradeCounterpartyFees_QNAME = new QName("http://www.sophis.net/reporting", "counterpartyFees");
    private final static QName _TradeReference_QNAME = new QName("http://www.sophis.net/reporting", "reference");
    private final static QName _TradeBankANIntermediaryBankCpty_QNAME = new QName("http://www.sophis.net/reporting", "bankANIntermediaryBankCpty");
    private final static QName _TradeBrokerFees_QNAME = new QName("http://www.sophis.net/reporting", "brokerFees");
    private final static QName _TradePortfolio_QNAME = new QName("http://www.sophis.net/reporting", "portfolio");
    private final static QName _TradeGrossAmount_QNAME = new QName("http://www.sophis.net/reporting", "grossAmount");
    private final static QName _TradeSettlementDate_QNAME = new QName("http://www.sophis.net/reporting", "settlementDate");
    private final static QName _TradeBeneficiaryEntity_QNAME = new QName("http://www.sophis.net/reporting", "beneficiaryEntity");
    private final static QName _TradeStatusGroup_QNAME = new QName("http://www.sophis.net/reporting", "statusGroup");
    private final static QName _TradeMaturity_QNAME = new QName("http://www.sophis.net/reporting", "maturity");
    private final static QName _TradeBankCpty_QNAME = new QName("http://www.sophis.net/reporting", "bankCpty");
    private final static QName _TradeIntermediaryBankCpty_QNAME = new QName("http://www.sophis.net/reporting", "intermediaryBankCpty");
    private final static QName _TradeName_QNAME = new QName("http://www.sophis.net/reporting", "name");
    private final static QName _TradePaymentMethod_QNAME = new QName("http://www.sophis.net/reporting", "paymentMethod");
    private final static QName _TradeAccruedAmount2_QNAME = new QName("http://www.sophis.net/reporting", "accruedAmount2");
    private final static QName _TradeCouponDate_QNAME = new QName("http://www.sophis.net/reporting", "couponDate");
    private final static QName _TradeBeneficiaryANBankEntity_QNAME = new QName("http://www.sophis.net/reporting", "beneficiaryANBankEntity");
    private final static QName _TradeCommissionSpreadRate_QNAME = new QName("http://www.sophis.net/reporting", "commissionSpreadRate");
    private final static QName _TradeStatus_QNAME = new QName("http://www.sophis.net/reporting", "status");
    private final static QName _TradeExecutionId_QNAME = new QName("http://www.sophis.net/reporting", "executionId");
    private final static QName _TradeKindOfInstrument_QNAME = new QName("http://www.sophis.net/reporting", "kindOfInstrument");
    private final static QName _TradePortfolioId_QNAME = new QName("http://www.sophis.net/reporting", "portfolioId");
    private final static QName _TradeBankEntity_QNAME = new QName("http://www.sophis.net/reporting", "bankEntity");
    private final static QName _TradeBeneficiaryCpty_QNAME = new QName("http://www.sophis.net/reporting", "beneficiaryCpty");
    private final static QName _TradeUnderlyingName_QNAME = new QName("http://www.sophis.net/reporting", "underlyingName");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.sophis.reporting
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TradeSourceDatesSettings }
     * 
     */
    public TradeSourceDatesSettings createTradeSourceDatesSettings() {
        return new TradeSourceDatesSettings();
    }

    /**
     * Create an instance of {@link TradeSourcePortfolioSettings }
     * 
     */
    public TradeSourcePortfolioSettings createTradeSourcePortfolioSettings() {
        return new TradeSourcePortfolioSettings();
    }

    /**
     * Create an instance of {@link TradeSourceSettings }
     * 
     */
    public TradeSourceSettings createTradeSourceSettings() {
        return new TradeSourceSettings();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Trades }
     * 
     */
    public Trades createTrades() {
        return new Trades();
    }

    /**
     * Create an instance of {@link Default0 }
     * 
     */
    public Default0 createDefault0() {
        return new Default0();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link TradeSourceBackOfficeSettings }
     * 
     */
    public TradeSourceBackOfficeSettings createTradeSourceBackOfficeSettings() {
        return new TradeSourceBackOfficeSettings();
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link GroupCriteria }
     * 
     */
    public GroupCriteria createGroupCriteria() {
        return new GroupCriteria();
    }

    /**
     * Create an instance of {@link Tradegroup }
     * 
     */
    public Tradegroup createTradegroup() {
        return new Tradegroup();
    }

    /**
     * Create an instance of {@link TradeSourceInstrumentSettings }
     * 
     */
    public TradeSourceInstrumentSettings createTradeSourceInstrumentSettings() {
        return new TradeSourceInstrumentSettings();
    }

    /**
     * Create an instance of {@link TradeSourcePartiesSettings }
     * 
     */
    public TradeSourcePartiesSettings createTradeSourcePartiesSettings() {
        return new TradeSourcePartiesSettings();
    }

    /**
     * Create an instance of {@link Trade }
     * 
     */
    public Trade createTrade() {
        return new Trade();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Root }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "root")
    public JAXBElement<Root> createRoot(Root value) {
        return new JAXBElement<Root>(_Root_QNAME, Root.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "underlyingReference", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeUnderlyingReference(String value) {
        return new JAXBElement<String>(_TradeUnderlyingReference_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "currency", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeCurrency(String value) {
        return new JAXBElement<String>(_TradeCurrency_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "changeRate", scope = Trade.class)
    public JAXBElement<Double> createTradeChangeRate(Double value) {
        return new JAXBElement<Double>(_TradeChangeRate_QNAME, Double.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "componentReference", scope = Trade.class)
    public JAXBElement<Long> createTradeComponentReference(Long value) {
        return new JAXBElement<Long>(_TradeComponentReference_QNAME, Long.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "beneficiaryANBankCpty", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeBeneficiaryANBankCpty(String value) {
        return new JAXBElement<String>(_TradeBeneficiaryANBankCpty_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "kindOfOption", scope = Trade.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTradeKindOfOption(String value) {
        return new JAXBElement<String>(_TradeKindOfOption_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "nominal", scope = Trade.class)
    public JAXBElement<Double> createTradeNominal(Double value) {
        return new JAXBElement<Double>(_TradeNominal_QNAME, Double.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "internalOrderId", scope = Trade.class)
    public JAXBElement<Integer> createTradeInternalOrderId(Integer value) {
        return new JAXBElement<Integer>(_TradeInternalOrderId_QNAME, Integer.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "priceType", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradePriceType(String value) {
        return new JAXBElement<String>(_TradePriceType_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "negotiationDate", scope = Trade.class)
    public JAXBElement<XMLGregorianCalendar> createTradeNegotiationDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TradeNegotiationDate_QNAME, XMLGregorianCalendar.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "right", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeRight(String value) {
        return new JAXBElement<String>(_TradeRight_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "tradeDate", scope = Trade.class)
    public JAXBElement<XMLGregorianCalendar> createTradeTradeDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TradeTradeDate_QNAME, XMLGregorianCalendar.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "valueDate", scope = Trade.class)
    public JAXBElement<XMLGregorianCalendar> createTradeValueDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TradeValueDate_QNAME, XMLGregorianCalendar.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "broker", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeBroker(String value) {
        return new JAXBElement<String>(_TradeBroker_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "parentId", scope = Trade.class)
    public JAXBElement<Long> createTradeParentId(Long value) {
        return new JAXBElement<Long>(_TradeParentId_QNAME, Long.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "instrumentReference", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeInstrumentReference(String value) {
        return new JAXBElement<String>(_TradeInstrumentReference_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "sicovam", scope = Trade.class)
    public JAXBElement<Integer> createTradeSicovam(Integer value) {
        return new JAXBElement<Integer>(_TradeSicovam_QNAME, Integer.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "instrumentType", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeInstrumentType(String value) {
        return new JAXBElement<String>(_TradeInstrumentType_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "pnLDate", scope = Trade.class)
    public JAXBElement<XMLGregorianCalendar> createTradePnLDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TradePnLDate_QNAME, XMLGregorianCalendar.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "fxCcy2", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeFxCcy2(String value) {
        return new JAXBElement<String>(_TradeFxCcy2_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "quantity", scope = Trade.class)
    public JAXBElement<Double> createTradeQuantity(Double value) {
        return new JAXBElement<Double>(_TradeQuantity_QNAME, Double.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "fxCcy1", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeFxCcy1(String value) {
        return new JAXBElement<String>(_TradeFxCcy1_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "netAmount", scope = Trade.class)
    public JAXBElement<Double> createTradeNetAmount(Double value) {
        return new JAXBElement<Double>(_TradeNetAmount_QNAME, Double.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "strike", scope = Trade.class)
    public JAXBElement<Double> createTradeStrike(Double value) {
        return new JAXBElement<Double>(_TradeStrike_QNAME, Double.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "counterparty", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeCounterparty(String value) {
        return new JAXBElement<String>(_TradeCounterparty_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "time", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeTime(String value) {
        return new JAXBElement<String>(_TradeTime_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "paymentDate", scope = Trade.class)
    public JAXBElement<XMLGregorianCalendar> createTradePaymentDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TradePaymentDate_QNAME, XMLGregorianCalendar.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "entity", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeEntity(String value) {
        return new JAXBElement<String>(_TradeEntity_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "tradeId", scope = Trade.class)
    public JAXBElement<Long> createTradeTradeId(Long value) {
        return new JAXBElement<Long>(_TradeTradeId_QNAME, Long.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "underlyingIsin", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeUnderlyingIsin(String value) {
        return new JAXBElement<String>(_TradeUnderlyingIsin_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "fund", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeFund(String value) {
        return new JAXBElement<String>(_TradeFund_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "netPrice", scope = Trade.class)
    public JAXBElement<Double> createTradeNetPrice(Double value) {
        return new JAXBElement<Double>(_TradeNetPrice_QNAME, Double.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "grossPrice", scope = Trade.class)
    public JAXBElement<Double> createTradeGrossPrice(Double value) {
        return new JAXBElement<Double>(_TradeGrossPrice_QNAME, Double.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "instrumentAllotment", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeInstrumentAllotment(String value) {
        return new JAXBElement<String>(_TradeInstrumentAllotment_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "instrumentMarket", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeInstrumentMarket(String value) {
        return new JAXBElement<String>(_TradeInstrumentMarket_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "kernelWorkflow", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeKernelWorkflow(String value) {
        return new JAXBElement<String>(_TradeKernelWorkflow_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "currencyType", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeCurrencyType(String value) {
        return new JAXBElement<String>(_TradeCurrencyType_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "ident", scope = Trade.class)
    public JAXBElement<Long> createTradeIdent(Long value) {
        return new JAXBElement<Long>(_TradeIdent_QNAME, Long.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "fxNominalCcy1", scope = Trade.class)
    public JAXBElement<Double> createTradeFxNominalCcy1(Double value) {
        return new JAXBElement<Double>(_TradeFxNominalCcy1_QNAME, Double.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "fxNominalCcy2", scope = Trade.class)
    public JAXBElement<Double> createTradeFxNominalCcy2(Double value) {
        return new JAXBElement<Double>(_TradeFxNominalCcy2_QNAME, Double.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "instrumentCurrency", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeInstrumentCurrency(String value) {
        return new JAXBElement<String>(_TradeInstrumentCurrency_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "marketFees", scope = Trade.class)
    public JAXBElement<Double> createTradeMarketFees(Double value) {
        return new JAXBElement<Double>(_TradeMarketFees_QNAME, Double.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "businessEvent", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeBusinessEvent(String value) {
        return new JAXBElement<String>(_TradeBusinessEvent_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "accruedCoupon", scope = Trade.class)
    public JAXBElement<Double> createTradeAccruedCoupon(Double value) {
        return new JAXBElement<Double>(_TradeAccruedCoupon_QNAME, Double.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "counterpartyFees", scope = Trade.class)
    public JAXBElement<Double> createTradeCounterpartyFees(Double value) {
        return new JAXBElement<Double>(_TradeCounterpartyFees_QNAME, Double.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "reference", scope = Trade.class)
    public JAXBElement<Long> createTradeReference(Long value) {
        return new JAXBElement<Long>(_TradeReference_QNAME, Long.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "bankANIntermediaryBankCpty", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeBankANIntermediaryBankCpty(String value) {
        return new JAXBElement<String>(_TradeBankANIntermediaryBankCpty_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "brokerFees", scope = Trade.class)
    public JAXBElement<Double> createTradeBrokerFees(Double value) {
        return new JAXBElement<Double>(_TradeBrokerFees_QNAME, Double.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "portfolio", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradePortfolio(String value) {
        return new JAXBElement<String>(_TradePortfolio_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "grossAmount", scope = Trade.class)
    public JAXBElement<Double> createTradeGrossAmount(Double value) {
        return new JAXBElement<Double>(_TradeGrossAmount_QNAME, Double.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "settlementDate", scope = Trade.class)
    public JAXBElement<XMLGregorianCalendar> createTradeSettlementDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TradeSettlementDate_QNAME, XMLGregorianCalendar.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "beneficiaryEntity", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeBeneficiaryEntity(String value) {
        return new JAXBElement<String>(_TradeBeneficiaryEntity_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "statusGroup", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeStatusGroup(String value) {
        return new JAXBElement<String>(_TradeStatusGroup_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "maturity", scope = Trade.class)
    public JAXBElement<XMLGregorianCalendar> createTradeMaturity(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TradeMaturity_QNAME, XMLGregorianCalendar.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "bankCpty", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeBankCpty(String value) {
        return new JAXBElement<String>(_TradeBankCpty_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "intermediaryBankCpty", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeIntermediaryBankCpty(String value) {
        return new JAXBElement<String>(_TradeIntermediaryBankCpty_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "name", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeName(String value) {
        return new JAXBElement<String>(_TradeName_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "paymentMethod", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradePaymentMethod(String value) {
        return new JAXBElement<String>(_TradePaymentMethod_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "accruedAmount2", scope = Trade.class)
    public JAXBElement<Double> createTradeAccruedAmount2(Double value) {
        return new JAXBElement<Double>(_TradeAccruedAmount2_QNAME, Double.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "couponDate", scope = Trade.class)
    public JAXBElement<XMLGregorianCalendar> createTradeCouponDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_TradeCouponDate_QNAME, XMLGregorianCalendar.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "beneficiaryANBankEntity", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeBeneficiaryANBankEntity(String value) {
        return new JAXBElement<String>(_TradeBeneficiaryANBankEntity_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "commissionSpreadRate", scope = Trade.class)
    public JAXBElement<Double> createTradeCommissionSpreadRate(Double value) {
        return new JAXBElement<Double>(_TradeCommissionSpreadRate_QNAME, Double.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "status", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeStatus(String value) {
        return new JAXBElement<String>(_TradeStatus_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "executionId", scope = Trade.class)
    public JAXBElement<Long> createTradeExecutionId(Long value) {
        return new JAXBElement<Long>(_TradeExecutionId_QNAME, Long.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "kindOfInstrument", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeKindOfInstrument(String value) {
        return new JAXBElement<String>(_TradeKindOfInstrument_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "portfolioId", scope = Trade.class)
    public JAXBElement<Integer> createTradePortfolioId(Integer value) {
        return new JAXBElement<Integer>(_TradePortfolioId_QNAME, Integer.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "bankEntity", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeBankEntity(String value) {
        return new JAXBElement<String>(_TradeBankEntity_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "beneficiaryCpty", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeBeneficiaryCpty(String value) {
        return new JAXBElement<String>(_TradeBeneficiaryCpty_QNAME, String.class, Trade.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sophis.net/reporting", name = "underlyingName", scope = Trade.class)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    public JAXBElement<String> createTradeUnderlyingName(String value) {
        return new JAXBElement<String>(_TradeUnderlyingName_QNAME, String.class, Trade.class, value);
    }

}
