//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.03 at 10:42:35 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sophis.net/reporting", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package net.sophis.reporting;
