//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.03 at 10:42:35 PM CEST 
//


package net.sophis.reporting;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Trade complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Trade">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="accruedAmount2" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="accruedCoupon" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="beneficiaryCpty" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="beneficiaryEntity" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="broker" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="brokerFees" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="businessEvent" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="changeRate" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="commissionSpreadRate" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="componentReference" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="counterparty" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="counterpartyFees" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="currencyType" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="entity" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="executionId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="grossAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="grossPrice" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="ident" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="instrumentAllotment" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="instrumentCurrency" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="instrumentReference" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="instrumentType" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="internalOrderId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="kernelWorkflow" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="kindOfInstrument" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="marketFees" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="negotiationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="netAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="netPrice" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="nominal" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="parentId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="paymentDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="paymentMethod" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="pnLDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="portfolio" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="portfolioId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="priceType" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="reference" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="right" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="sicovam" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="statusGroup" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="strike" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="tradeDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="tradeId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="underlyingName" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="underlyingReference" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="valueDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="bankCpty" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="bankANIntermediaryBankCpty" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="beneficiaryANBankCpty" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="intermediaryBankCpty" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="kindOfOption" type="{http://sophis.net/sophis/common}Char" minOccurs="0"/>
 *         &lt;element name="maturity" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="fund" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="instrumentMarket" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="underlyingIsin" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="bankEntity" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="beneficiaryANBankEntity" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="fxCcy1" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="fxCcy2" type="{http://www.w3.org/2001/XMLSchema}normalizedString" minOccurs="0"/>
 *         &lt;element name="fxNominalCcy1" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="fxNominalCcy2" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="settlementDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="couponDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="tradeType" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="positionType" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Trade", propOrder = {

})
public class Trade {

    @XmlElementRef(name = "accruedAmount2", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Double> accruedAmount2;
    @XmlElementRef(name = "accruedCoupon", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Double> accruedCoupon;
    @XmlElementRef(name = "beneficiaryCpty", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> beneficiaryCpty;
    @XmlElementRef(name = "beneficiaryEntity", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> beneficiaryEntity;
    @XmlElementRef(name = "broker", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> broker;
    @XmlElementRef(name = "brokerFees", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Double> brokerFees;
    @XmlElementRef(name = "businessEvent", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> businessEvent;
    @XmlElementRef(name = "changeRate", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Double> changeRate;
    @XmlElementRef(name = "commissionSpreadRate", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Double> commissionSpreadRate;
    @XmlElementRef(name = "componentReference", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Long> componentReference;
    @XmlElementRef(name = "counterparty", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> counterparty;
    @XmlElementRef(name = "counterpartyFees", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Double> counterpartyFees;
    @XmlElementRef(name = "currency", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> currency;
    @XmlElementRef(name = "currencyType", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> currencyType;
    @XmlElementRef(name = "entity", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> entity;
    @XmlElementRef(name = "executionId", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Long> executionId;
    @XmlElementRef(name = "grossAmount", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Double> grossAmount;
    @XmlElementRef(name = "grossPrice", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Double> grossPrice;
    @XmlElementRef(name = "ident", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Long> ident;
    @XmlElementRef(name = "instrumentAllotment", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> instrumentAllotment;
    @XmlElementRef(name = "instrumentCurrency", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> instrumentCurrency;
    @XmlElementRef(name = "instrumentReference", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> instrumentReference;
    @XmlElementRef(name = "instrumentType", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> instrumentType;
    @XmlElementRef(name = "internalOrderId", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> internalOrderId;
    @XmlElementRef(name = "kernelWorkflow", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> kernelWorkflow;
    @XmlElementRef(name = "kindOfInstrument", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> kindOfInstrument;
    @XmlElementRef(name = "marketFees", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Double> marketFees;
    @XmlElementRef(name = "name", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> name;
    @XmlElementRef(name = "negotiationDate", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> negotiationDate;
    @XmlElementRef(name = "netAmount", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Double> netAmount;
    @XmlElementRef(name = "netPrice", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Double> netPrice;
    @XmlElementRef(name = "nominal", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Double> nominal;
    @XmlElementRef(name = "parentId", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Long> parentId;
    @XmlElementRef(name = "paymentDate", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> paymentDate;
    @XmlElementRef(name = "paymentMethod", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> paymentMethod;
    @XmlElementRef(name = "pnLDate", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> pnLDate;
    @XmlElementRef(name = "portfolio", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> portfolio;
    @XmlElementRef(name = "portfolioId", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> portfolioId;
    @XmlElementRef(name = "priceType", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> priceType;
    @XmlElementRef(name = "quantity", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Double> quantity;
    @XmlElementRef(name = "reference", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Long> reference;
    @XmlElementRef(name = "right", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> right;
    @XmlElementRef(name = "sicovam", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Integer> sicovam;
    @XmlElementRef(name = "status", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> status;
    @XmlElementRef(name = "statusGroup", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> statusGroup;
    @XmlElementRef(name = "strike", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Double> strike;
    @XmlElementRef(name = "time", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> time;
    @XmlElementRef(name = "tradeDate", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> tradeDate;
    @XmlElementRef(name = "tradeId", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Long> tradeId;
    @XmlElementRef(name = "underlyingName", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> underlyingName;
    @XmlElementRef(name = "underlyingReference", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> underlyingReference;
    @XmlElementRef(name = "valueDate", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> valueDate;
    @XmlElementRef(name = "bankCpty", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> bankCpty;
    @XmlElementRef(name = "bankANIntermediaryBankCpty", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> bankANIntermediaryBankCpty;
    @XmlElementRef(name = "beneficiaryANBankCpty", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> beneficiaryANBankCpty;
    @XmlElementRef(name = "intermediaryBankCpty", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> intermediaryBankCpty;
    @XmlElementRef(name = "kindOfOption", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> kindOfOption;
    @XmlElementRef(name = "maturity", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> maturity;
    @XmlElementRef(name = "fund", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> fund;
    @XmlElementRef(name = "instrumentMarket", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> instrumentMarket;
    @XmlElementRef(name = "underlyingIsin", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> underlyingIsin;
    @XmlElementRef(name = "bankEntity", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> bankEntity;
    @XmlElementRef(name = "beneficiaryANBankEntity", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> beneficiaryANBankEntity;
    @XmlElementRef(name = "fxCcy1", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> fxCcy1;
    @XmlElementRef(name = "fxCcy2", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<String> fxCcy2;
    @XmlElementRef(name = "fxNominalCcy1", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Double> fxNominalCcy1;
    @XmlElementRef(name = "fxNominalCcy2", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<Double> fxNominalCcy2;
    @XmlElementRef(name = "settlementDate", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> settlementDate;
    @XmlElementRef(name = "couponDate", namespace = "http://www.sophis.net/reporting", type = JAXBElement.class, required = false)
    protected JAXBElement<XMLGregorianCalendar> couponDate;
    @XmlAttribute(name = "tradeType", namespace = "http://www.sophis.net/reporting")
    protected Integer tradeType;
    @XmlAttribute(name = "positionType", namespace = "http://www.sophis.net/reporting")
    protected Integer positionType;

    /**
     * Gets the value of the accruedAmount2 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<Double> getAccruedAmount2() {
        return accruedAmount2;
    }

    /**
     * Sets the value of the accruedAmount2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setAccruedAmount2(JAXBElement<Double> value) {
        this.accruedAmount2 = ((JAXBElement<Double> ) value);
    }

    /**
     * Gets the value of the accruedCoupon property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<Double> getAccruedCoupon() {
        return accruedCoupon;
    }

    /**
     * Sets the value of the accruedCoupon property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setAccruedCoupon(JAXBElement<Double> value) {
        this.accruedCoupon = ((JAXBElement<Double> ) value);
    }

    /**
     * Gets the value of the beneficiaryCpty property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBeneficiaryCpty() {
        return beneficiaryCpty;
    }

    /**
     * Sets the value of the beneficiaryCpty property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBeneficiaryCpty(JAXBElement<String> value) {
        this.beneficiaryCpty = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the beneficiaryEntity property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBeneficiaryEntity() {
        return beneficiaryEntity;
    }

    /**
     * Sets the value of the beneficiaryEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBeneficiaryEntity(JAXBElement<String> value) {
        this.beneficiaryEntity = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the broker property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBroker() {
        return broker;
    }

    /**
     * Sets the value of the broker property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBroker(JAXBElement<String> value) {
        this.broker = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the brokerFees property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<Double> getBrokerFees() {
        return brokerFees;
    }

    /**
     * Sets the value of the brokerFees property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setBrokerFees(JAXBElement<Double> value) {
        this.brokerFees = ((JAXBElement<Double> ) value);
    }

    /**
     * Gets the value of the businessEvent property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBusinessEvent() {
        return businessEvent;
    }

    /**
     * Sets the value of the businessEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBusinessEvent(JAXBElement<String> value) {
        this.businessEvent = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the changeRate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<Double> getChangeRate() {
        return changeRate;
    }

    /**
     * Sets the value of the changeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setChangeRate(JAXBElement<Double> value) {
        this.changeRate = ((JAXBElement<Double> ) value);
    }

    /**
     * Gets the value of the commissionSpreadRate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<Double> getCommissionSpreadRate() {
        return commissionSpreadRate;
    }

    /**
     * Sets the value of the commissionSpreadRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setCommissionSpreadRate(JAXBElement<Double> value) {
        this.commissionSpreadRate = ((JAXBElement<Double> ) value);
    }

    /**
     * Gets the value of the componentReference property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getComponentReference() {
        return componentReference;
    }

    /**
     * Sets the value of the componentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setComponentReference(JAXBElement<Long> value) {
        this.componentReference = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the counterparty property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCounterparty() {
        return counterparty;
    }

    /**
     * Sets the value of the counterparty property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCounterparty(JAXBElement<String> value) {
        this.counterparty = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the counterpartyFees property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<Double> getCounterpartyFees() {
        return counterpartyFees;
    }

    /**
     * Sets the value of the counterpartyFees property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setCounterpartyFees(JAXBElement<Double> value) {
        this.counterpartyFees = ((JAXBElement<Double> ) value);
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCurrency(JAXBElement<String> value) {
        this.currency = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the currencyType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCurrencyType() {
        return currencyType;
    }

    /**
     * Sets the value of the currencyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCurrencyType(JAXBElement<String> value) {
        this.currencyType = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the entity property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getEntity() {
        return entity;
    }

    /**
     * Sets the value of the entity property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setEntity(JAXBElement<String> value) {
        this.entity = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the executionId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getExecutionId() {
        return executionId;
    }

    /**
     * Sets the value of the executionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setExecutionId(JAXBElement<Long> value) {
        this.executionId = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the grossAmount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<Double> getGrossAmount() {
        return grossAmount;
    }

    /**
     * Sets the value of the grossAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setGrossAmount(JAXBElement<Double> value) {
        this.grossAmount = ((JAXBElement<Double> ) value);
    }

    /**
     * Gets the value of the grossPrice property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<Double> getGrossPrice() {
        return grossPrice;
    }

    /**
     * Sets the value of the grossPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setGrossPrice(JAXBElement<Double> value) {
        this.grossPrice = ((JAXBElement<Double> ) value);
    }

    /**
     * Gets the value of the ident property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getIdent() {
        return ident;
    }

    /**
     * Sets the value of the ident property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setIdent(JAXBElement<Long> value) {
        this.ident = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the instrumentAllotment property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getInstrumentAllotment() {
        return instrumentAllotment;
    }

    /**
     * Sets the value of the instrumentAllotment property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setInstrumentAllotment(JAXBElement<String> value) {
        this.instrumentAllotment = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the instrumentCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getInstrumentCurrency() {
        return instrumentCurrency;
    }

    /**
     * Sets the value of the instrumentCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setInstrumentCurrency(JAXBElement<String> value) {
        this.instrumentCurrency = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the instrumentReference property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getInstrumentReference() {
        return instrumentReference;
    }

    /**
     * Sets the value of the instrumentReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setInstrumentReference(JAXBElement<String> value) {
        this.instrumentReference = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the instrumentType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getInstrumentType() {
        return instrumentType;
    }

    /**
     * Sets the value of the instrumentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setInstrumentType(JAXBElement<String> value) {
        this.instrumentType = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the internalOrderId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getInternalOrderId() {
        return internalOrderId;
    }

    /**
     * Sets the value of the internalOrderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setInternalOrderId(JAXBElement<Integer> value) {
        this.internalOrderId = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the kernelWorkflow property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getKernelWorkflow() {
        return kernelWorkflow;
    }

    /**
     * Sets the value of the kernelWorkflow property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setKernelWorkflow(JAXBElement<String> value) {
        this.kernelWorkflow = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the kindOfInstrument property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getKindOfInstrument() {
        return kindOfInstrument;
    }

    /**
     * Sets the value of the kindOfInstrument property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setKindOfInstrument(JAXBElement<String> value) {
        this.kindOfInstrument = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the marketFees property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<Double> getMarketFees() {
        return marketFees;
    }

    /**
     * Sets the value of the marketFees property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setMarketFees(JAXBElement<Double> value) {
        this.marketFees = ((JAXBElement<Double> ) value);
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setName(JAXBElement<String> value) {
        this.name = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the negotiationDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getNegotiationDate() {
        return negotiationDate;
    }

    /**
     * Sets the value of the negotiationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setNegotiationDate(JAXBElement<XMLGregorianCalendar> value) {
        this.negotiationDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the netAmount property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<Double> getNetAmount() {
        return netAmount;
    }

    /**
     * Sets the value of the netAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setNetAmount(JAXBElement<Double> value) {
        this.netAmount = ((JAXBElement<Double> ) value);
    }

    /**
     * Gets the value of the netPrice property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<Double> getNetPrice() {
        return netPrice;
    }

    /**
     * Sets the value of the netPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setNetPrice(JAXBElement<Double> value) {
        this.netPrice = ((JAXBElement<Double> ) value);
    }

    /**
     * Gets the value of the nominal property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<Double> getNominal() {
        return nominal;
    }

    /**
     * Sets the value of the nominal property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setNominal(JAXBElement<Double> value) {
        this.nominal = ((JAXBElement<Double> ) value);
    }

    /**
     * Gets the value of the parentId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getParentId() {
        return parentId;
    }

    /**
     * Sets the value of the parentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setParentId(JAXBElement<Long> value) {
        this.parentId = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the paymentDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getPaymentDate() {
        return paymentDate;
    }

    /**
     * Sets the value of the paymentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setPaymentDate(JAXBElement<XMLGregorianCalendar> value) {
        this.paymentDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the paymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * Sets the value of the paymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPaymentMethod(JAXBElement<String> value) {
        this.paymentMethod = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the pnLDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getPnLDate() {
        return pnLDate;
    }

    /**
     * Sets the value of the pnLDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setPnLDate(JAXBElement<XMLGregorianCalendar> value) {
        this.pnLDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the portfolio property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPortfolio() {
        return portfolio;
    }

    /**
     * Sets the value of the portfolio property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPortfolio(JAXBElement<String> value) {
        this.portfolio = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the portfolioId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getPortfolioId() {
        return portfolioId;
    }

    /**
     * Sets the value of the portfolioId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setPortfolioId(JAXBElement<Integer> value) {
        this.portfolioId = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the priceType property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPriceType() {
        return priceType;
    }

    /**
     * Sets the value of the priceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPriceType(JAXBElement<String> value) {
        this.priceType = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<Double> getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setQuantity(JAXBElement<Double> value) {
        this.quantity = ((JAXBElement<Double> ) value);
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setReference(JAXBElement<Long> value) {
        this.reference = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the right property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRight() {
        return right;
    }

    /**
     * Sets the value of the right property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRight(JAXBElement<String> value) {
        this.right = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the sicovam property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public JAXBElement<Integer> getSicovam() {
        return sicovam;
    }

    /**
     * Sets the value of the sicovam property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Integer }{@code >}
     *     
     */
    public void setSicovam(JAXBElement<Integer> value) {
        this.sicovam = ((JAXBElement<Integer> ) value);
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setStatus(JAXBElement<String> value) {
        this.status = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the statusGroup property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getStatusGroup() {
        return statusGroup;
    }

    /**
     * Sets the value of the statusGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setStatusGroup(JAXBElement<String> value) {
        this.statusGroup = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the strike property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<Double> getStrike() {
        return strike;
    }

    /**
     * Sets the value of the strike property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setStrike(JAXBElement<Double> value) {
        this.strike = ((JAXBElement<Double> ) value);
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTime(JAXBElement<String> value) {
        this.time = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the tradeDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getTradeDate() {
        return tradeDate;
    }

    /**
     * Sets the value of the tradeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setTradeDate(JAXBElement<XMLGregorianCalendar> value) {
        this.tradeDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the tradeId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public JAXBElement<Long> getTradeId() {
        return tradeId;
    }

    /**
     * Sets the value of the tradeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Long }{@code >}
     *     
     */
    public void setTradeId(JAXBElement<Long> value) {
        this.tradeId = ((JAXBElement<Long> ) value);
    }

    /**
     * Gets the value of the underlyingName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getUnderlyingName() {
        return underlyingName;
    }

    /**
     * Sets the value of the underlyingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setUnderlyingName(JAXBElement<String> value) {
        this.underlyingName = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the underlyingReference property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getUnderlyingReference() {
        return underlyingReference;
    }

    /**
     * Sets the value of the underlyingReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setUnderlyingReference(JAXBElement<String> value) {
        this.underlyingReference = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the valueDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getValueDate() {
        return valueDate;
    }

    /**
     * Sets the value of the valueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setValueDate(JAXBElement<XMLGregorianCalendar> value) {
        this.valueDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the bankCpty property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBankCpty() {
        return bankCpty;
    }

    /**
     * Sets the value of the bankCpty property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBankCpty(JAXBElement<String> value) {
        this.bankCpty = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the bankANIntermediaryBankCpty property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBankANIntermediaryBankCpty() {
        return bankANIntermediaryBankCpty;
    }

    /**
     * Sets the value of the bankANIntermediaryBankCpty property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBankANIntermediaryBankCpty(JAXBElement<String> value) {
        this.bankANIntermediaryBankCpty = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the beneficiaryANBankCpty property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBeneficiaryANBankCpty() {
        return beneficiaryANBankCpty;
    }

    /**
     * Sets the value of the beneficiaryANBankCpty property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBeneficiaryANBankCpty(JAXBElement<String> value) {
        this.beneficiaryANBankCpty = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the intermediaryBankCpty property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getIntermediaryBankCpty() {
        return intermediaryBankCpty;
    }

    /**
     * Sets the value of the intermediaryBankCpty property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setIntermediaryBankCpty(JAXBElement<String> value) {
        this.intermediaryBankCpty = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the kindOfOption property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getKindOfOption() {
        return kindOfOption;
    }

    /**
     * Sets the value of the kindOfOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setKindOfOption(JAXBElement<String> value) {
        this.kindOfOption = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the maturity property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getMaturity() {
        return maturity;
    }

    /**
     * Sets the value of the maturity property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setMaturity(JAXBElement<XMLGregorianCalendar> value) {
        this.maturity = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the fund property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFund() {
        return fund;
    }

    /**
     * Sets the value of the fund property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFund(JAXBElement<String> value) {
        this.fund = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the instrumentMarket property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getInstrumentMarket() {
        return instrumentMarket;
    }

    /**
     * Sets the value of the instrumentMarket property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setInstrumentMarket(JAXBElement<String> value) {
        this.instrumentMarket = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the underlyingIsin property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getUnderlyingIsin() {
        return underlyingIsin;
    }

    /**
     * Sets the value of the underlyingIsin property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setUnderlyingIsin(JAXBElement<String> value) {
        this.underlyingIsin = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the bankEntity property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBankEntity() {
        return bankEntity;
    }

    /**
     * Sets the value of the bankEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBankEntity(JAXBElement<String> value) {
        this.bankEntity = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the beneficiaryANBankEntity property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getBeneficiaryANBankEntity() {
        return beneficiaryANBankEntity;
    }

    /**
     * Sets the value of the beneficiaryANBankEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBeneficiaryANBankEntity(JAXBElement<String> value) {
        this.beneficiaryANBankEntity = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the fxCcy1 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFxCcy1() {
        return fxCcy1;
    }

    /**
     * Sets the value of the fxCcy1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFxCcy1(JAXBElement<String> value) {
        this.fxCcy1 = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the fxCcy2 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFxCcy2() {
        return fxCcy2;
    }

    /**
     * Sets the value of the fxCcy2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFxCcy2(JAXBElement<String> value) {
        this.fxCcy2 = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the fxNominalCcy1 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<Double> getFxNominalCcy1() {
        return fxNominalCcy1;
    }

    /**
     * Sets the value of the fxNominalCcy1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setFxNominalCcy1(JAXBElement<Double> value) {
        this.fxNominalCcy1 = ((JAXBElement<Double> ) value);
    }

    /**
     * Gets the value of the fxNominalCcy2 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public JAXBElement<Double> getFxNominalCcy2() {
        return fxNominalCcy2;
    }

    /**
     * Sets the value of the fxNominalCcy2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Double }{@code >}
     *     
     */
    public void setFxNominalCcy2(JAXBElement<Double> value) {
        this.fxNominalCcy2 = ((JAXBElement<Double> ) value);
    }

    /**
     * Gets the value of the settlementDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getSettlementDate() {
        return settlementDate;
    }

    /**
     * Sets the value of the settlementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setSettlementDate(JAXBElement<XMLGregorianCalendar> value) {
        this.settlementDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the couponDate property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public JAXBElement<XMLGregorianCalendar> getCouponDate() {
        return couponDate;
    }

    /**
     * Sets the value of the couponDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     *     
     */
    public void setCouponDate(JAXBElement<XMLGregorianCalendar> value) {
        this.couponDate = ((JAXBElement<XMLGregorianCalendar> ) value);
    }

    /**
     * Gets the value of the tradeType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTradeType() {
        return tradeType;
    }

    /**
     * Sets the value of the tradeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTradeType(Integer value) {
        this.tradeType = value;
    }

    /**
     * Gets the value of the positionType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPositionType() {
        return positionType;
    }

    /**
     * Sets the value of the positionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPositionType(Integer value) {
        this.positionType = value;
    }

}
