//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.03 at 10:42:35 PM CEST 
//


package net.sophis.reporting;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Tradegroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tradegroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="groupCriteria" type="{http://www.sophis.net/reporting}GroupCriteria" minOccurs="0"/>
 *         &lt;element name="trades" type="{http://www.sophis.net/reporting}Trades" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tradegroup", propOrder = {

})
public class Tradegroup {

    protected GroupCriteria groupCriteria;
    protected Trades trades;

    /**
     * Gets the value of the groupCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link GroupCriteria }
     *     
     */
    public GroupCriteria getGroupCriteria() {
        return groupCriteria;
    }

    /**
     * Sets the value of the groupCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupCriteria }
     *     
     */
    public void setGroupCriteria(GroupCriteria value) {
        this.groupCriteria = value;
    }

    /**
     * Gets the value of the trades property.
     * 
     * @return
     *     possible object is
     *     {@link Trades }
     *     
     */
    public Trades getTrades() {
        return trades;
    }

    /**
     * Sets the value of the trades property.
     * 
     * @param value
     *     allowed object is
     *     {@link Trades }
     *     
     */
    public void setTrades(Trades value) {
        this.trades = value;
    }

}
