//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.03 at 10:42:35 PM CEST 
//


package net.sophis.reporting;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TradeSourceSettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TradeSourceSettings">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="tradeSourcePortfolioSettings" type="{http://www.sophis.net/reporting}TradeSourcePortfolioSettings" minOccurs="0"/>
 *         &lt;element name="tradeSourceDatesSettings" type="{http://www.sophis.net/reporting}TradeSourceDatesSettings" minOccurs="0"/>
 *         &lt;element name="tradeSourceInstrumentSettings" type="{http://www.sophis.net/reporting}TradeSourceInstrumentSettings" minOccurs="0"/>
 *         &lt;element name="tradeSourcePartiesSettings" type="{http://www.sophis.net/reporting}TradeSourcePartiesSettings" minOccurs="0"/>
 *         &lt;element name="tradeSourceBackOfficeSettings" type="{http://www.sophis.net/reporting}TradeSourceBackOfficeSettings" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TradeSourceSettings", propOrder = {

})
public class TradeSourceSettings {

    protected TradeSourcePortfolioSettings tradeSourcePortfolioSettings;
    protected TradeSourceDatesSettings tradeSourceDatesSettings;
    protected TradeSourceInstrumentSettings tradeSourceInstrumentSettings;
    protected TradeSourcePartiesSettings tradeSourcePartiesSettings;
    protected TradeSourceBackOfficeSettings tradeSourceBackOfficeSettings;

    /**
     * Gets the value of the tradeSourcePortfolioSettings property.
     * 
     * @return
     *     possible object is
     *     {@link TradeSourcePortfolioSettings }
     *     
     */
    public TradeSourcePortfolioSettings getTradeSourcePortfolioSettings() {
        return tradeSourcePortfolioSettings;
    }

    /**
     * Sets the value of the tradeSourcePortfolioSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeSourcePortfolioSettings }
     *     
     */
    public void setTradeSourcePortfolioSettings(TradeSourcePortfolioSettings value) {
        this.tradeSourcePortfolioSettings = value;
    }

    /**
     * Gets the value of the tradeSourceDatesSettings property.
     * 
     * @return
     *     possible object is
     *     {@link TradeSourceDatesSettings }
     *     
     */
    public TradeSourceDatesSettings getTradeSourceDatesSettings() {
        return tradeSourceDatesSettings;
    }

    /**
     * Sets the value of the tradeSourceDatesSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeSourceDatesSettings }
     *     
     */
    public void setTradeSourceDatesSettings(TradeSourceDatesSettings value) {
        this.tradeSourceDatesSettings = value;
    }

    /**
     * Gets the value of the tradeSourceInstrumentSettings property.
     * 
     * @return
     *     possible object is
     *     {@link TradeSourceInstrumentSettings }
     *     
     */
    public TradeSourceInstrumentSettings getTradeSourceInstrumentSettings() {
        return tradeSourceInstrumentSettings;
    }

    /**
     * Sets the value of the tradeSourceInstrumentSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeSourceInstrumentSettings }
     *     
     */
    public void setTradeSourceInstrumentSettings(TradeSourceInstrumentSettings value) {
        this.tradeSourceInstrumentSettings = value;
    }

    /**
     * Gets the value of the tradeSourcePartiesSettings property.
     * 
     * @return
     *     possible object is
     *     {@link TradeSourcePartiesSettings }
     *     
     */
    public TradeSourcePartiesSettings getTradeSourcePartiesSettings() {
        return tradeSourcePartiesSettings;
    }

    /**
     * Sets the value of the tradeSourcePartiesSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeSourcePartiesSettings }
     *     
     */
    public void setTradeSourcePartiesSettings(TradeSourcePartiesSettings value) {
        this.tradeSourcePartiesSettings = value;
    }

    /**
     * Gets the value of the tradeSourceBackOfficeSettings property.
     * 
     * @return
     *     possible object is
     *     {@link TradeSourceBackOfficeSettings }
     *     
     */
    public TradeSourceBackOfficeSettings getTradeSourceBackOfficeSettings() {
        return tradeSourceBackOfficeSettings;
    }

    /**
     * Sets the value of the tradeSourceBackOfficeSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link TradeSourceBackOfficeSettings }
     *     
     */
    public void setTradeSourceBackOfficeSettings(TradeSourceBackOfficeSettings value) {
        this.tradeSourceBackOfficeSettings = value;
    }

}
